application: disrupted-continuum
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /bower_components
  static_dir: bower_components

- url: /name
  script: main.app

- url: /
  static_files: app/index.html
  upload: app/index\.html

- url: /
  static_dir: app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
