application: disrupted-continuum
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: ../styles/css
  static_dir: styles
- url: ../scripts/js
  static_dir: scripts
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
